"use client";

/**
 * The generated radiology report, in every form the component produced it.
 *
 * WHY THREE VIEWS AND NOT ONE
 * ---------------------------
 * Ported from Component 01's own console, where it does real work rather than
 * decoration. A generated report shown alone asks to be trusted; shown beside
 * the decoder's exact output and the radiologist's original, it can be checked.
 *
 *   AI report          the cleaned text, what a reader would act on
 *   Raw decoder output the exact generation, special tokens and all. It is
 *                      nearly identical to the cleaned text, and that is the
 *                      point: this system removed prior-study language from the
 *                      training TARGETS rather than post-processing it out of
 *                      the output, so the model never learned to write
 *                      "compared to the prior study". Fabricated prior-study
 *                      references measure 0.0000 across 4,722 test reports.
 *                      Showing the raw output is what makes that checkable.
 *   Radiologist report the original dictation, available only when the
 *                      uploaded file matches an indexed test study.
 *
 * The impression is split from the findings because that is how a report is
 * read: the first sentence carries the conclusion, and a reader scanning a
 * worklist needs it separated rather than buried in a paragraph.
 */
import { useMemo, useState } from "react";

import { frame } from "@/components/ui";
import { cn } from "@/lib/format";

type ViewMode = "cleaned" | "raw" | "truth";

const RAW_NOTE =
  "The exact decoder output, including special tokens. It is almost identical " +
  "to the AI report because this system removes artefacts from the training " +
  "targets rather than from the output — the model never learned to write " +
  "“compared to the prior study”. Fabricated prior-study references measure " +
  "0.0000 across 4,722 test reports.";

const TRUTH_NOTE =
  "The report as dictated, prior-study references and all. Shown only when the " +
  "uploaded file matches an indexed test study.";

const CLEANED_NOTE =
  "Generated by BioBART from the same visual features the classifier used, then " +
  "cleaned for display.";

/** First sentence is the impression; the remainder is the findings. */
function split(text: string): { impression: string; findings: string } {
  const sentences = text
    .split(". ")
    .map((part) => part.trim())
    .filter(Boolean)
    .map((part) => (part.endsWith(".") ? part : `${part}.`));

  if (sentences.length <= 2) return { impression: text.trim(), findings: "" };

  // A very short second sentence usually belongs with the first — "No acute
  // cardiopulmonary process." reads as part of the impression, not a finding.
  const second = sentences[1] ?? "";
  const impression = sentences[0] + (second.length < 60 ? ` ${second}` : "");
  return { impression, findings: text.slice(impression.length).trim() };
}

/** Marks a tokenizer control token so it cannot be mistaken for generated text. */
function SpecialToken({ children }: { children: React.ReactNode }) {
  return (
    <span className="rounded border border-verdict-deferred/30 bg-verdict-deferred/10 px-1 py-px font-mono text-[0.75rem] font-semibold text-verdict-deferred">
      {children}
    </span>
  );
}

/**
 * Split verbatim decoder output so control tokens render as chips.
 *
 * Without this the tokens read as if the model had written them. They are
 * artefacts of the tokenizer, and the difference matters here: this panel
 * exists to show that the ONLY difference between the raw and cleaned text is
 * these markers.
 */
/* Two regexes on purpose. A /g regex is stateful: `.test()` advances
   `lastIndex` and the next call resumes from there, so reusing the splitting
   pattern to classify each part returns alternating wrong answers. The
   classifier is a separate, anchored, non-global pattern. */
const SPECIAL_SPLIT = /(<\/?s>|<pad>|<unk>|<mask>)/g;
const IS_SPECIAL = /^<\/?(?:s|pad|unk|mask)>$/;

function tokenise(text: string): React.ReactNode[] {
  return text
    .split(SPECIAL_SPLIT)
    .filter(Boolean)
    .map((part, index) =>
      IS_SPECIAL.test(part) ? (
        <SpecialToken key={index}>{part}</SpecialToken>
      ) : (
        <span key={index}>{part}</span>
      ),
    );
}

export function ReportViewer({
  cleaned,
  raw,
  groundTruth,
  prompt,
  bare,
}: {
  cleaned?: string | null;
  raw?: string | null;
  groundTruth?: string | null;
  /** The conditioning string the classifier handed the report generator. */
  prompt?: string | null;
  bare?: boolean;
}) {
  const modes = useMemo(() => {
    const available: { id: ViewMode; label: string }[] = [];
    if (cleaned) available.push({ id: "cleaned", label: "AI report" });
    // Only offered when it differs — an identical tab is a control that does
    // nothing, and invites the reader to wonder what they missed.
    if (raw && raw !== cleaned) available.push({ id: "raw", label: "Raw output" });
    if (groundTruth) available.push({ id: "truth", label: "Radiologist" });
    return available;
  }, [cleaned, raw, groundTruth]);

  const [mode, setMode] = useState<ViewMode>("cleaned");
  const [copied, setCopied] = useState(false);

  const { Frame, FrameHeader, FrameBody } = frame(bare);

  if (modes.length === 0) return null;
  const active = modes.some((m) => m.id === mode) ? mode : (modes[0]?.id ?? "cleaned");

  const text =
    (active === "truth" ? groundTruth : active === "raw" ? raw : cleaned) ?? "";
  const note =
    active === "truth" ? TRUTH_NOTE : active === "raw" ? RAW_NOTE : CLEANED_NOTE;
  const { impression, findings } = split(text);

  async function copy() {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard access can be denied; the text is selectable either way.
    }
  }

  return (
    <Frame>
      <FrameHeader
        title={active === "truth" ? "Radiologist report" : "Generated report"}
        description={note}
        actions={
          <button
            type="button"
            onClick={copy}
            className="rounded-md border border-line bg-surface px-3 py-1.5 text-[0.8125rem] font-semibold text-ink-muted transition-colors hover:bg-surface-2 hover:text-ink"
          >
            {copied ? "Copied" : "Copy"}
          </button>
        }
      />
      <FrameBody className="space-y-4">
        {modes.length > 1 && (
          <div className="segmented">
            {modes.map((m) => (
              <button
                key={m.id}
                type="button"
                onClick={() => setMode(m.id)}
                className={cn("segmented-btn", active === m.id && "active")}
              >
                {m.label}
              </button>
            ))}
          </div>
        )}

        {/* The raw view is not prose and must not be sectioned like prose.
            Running it through the impression/findings split put "</s><s>" in
            the Impression heading, which reads as a broken report rather than
            as an unedited generation. Shown verbatim instead, with the
            tokenizer's own markers called out as what they are. */}
        {active === "raw" ? (
          <div>
            <p className="eyebrow mb-2">Verbatim decoder output</p>
            <p className="whitespace-pre-wrap break-words rounded-lg border border-line bg-surface-2 p-4 font-mono text-[0.8125rem] leading-relaxed text-ink">
              {tokenise(text)}
            </p>
            <p className="mt-2.5 text-[0.8125rem] leading-relaxed text-ink-faint">
              <SpecialToken>{"<s>"}</SpecialToken> and{" "}
              <SpecialToken>{"</s>"}</SpecialToken> are the tokenizer&apos;s
              start- and end-of-sequence markers, not generated text. Strip them
              and this is character-for-character the AI report — which is the
              claim this view exists to let you check.
            </p>
          </div>
        ) : (
          <>
            <div>
              <p className="eyebrow mb-1.5">Impression</p>
              <p className="text-[0.9375rem] font-semibold leading-relaxed text-ink">
                {impression || "—"}
              </p>
            </div>

            {findings && (
              <div className="border-t border-line pt-4">
                <p className="eyebrow mb-1.5">Findings</p>
                <p className="whitespace-pre-wrap text-sm leading-relaxed text-ink-muted">
                  {findings}
                </p>
              </div>
            )}
          </>
        )}

        {/* The conditioning string is the join between the two models: it is
            what the classifier actually told the generator, so a reader can see
            whether the text follows from the findings or from the image alone.
            Hidden on the radiologist's report, which no model conditioned. */}
        {prompt && active !== "truth" && (
          <div className="border-t border-line pt-4">
            <p className="eyebrow mb-1.5">Conditioned on</p>
            <p className="font-mono text-[0.8125rem] leading-relaxed text-ink-muted">
              {prompt}
            </p>
            <p className="mt-2 text-[0.8125rem] leading-relaxed text-ink-faint">
              What the classifier passed to the report generator. The text above
              was written from this, not from the image directly.
            </p>
          </div>
        )}
      </FrameBody>
    </Frame>
  );
}
