"""
Strip the " (1)" zip-extraction suffix from every path inside Component 02.

WHY
---
Component 02 was distributed as a zip that de-duplicated every name, so on disk
the package is `src (1)/` holding `models (1).py`, `pipeline (1).py`, and the
dataset is `records500 (1)/00000 (1)/00001_hr (1).hea`. The source inside still
says `from .models import ...` and `src/paths.py` still looks for
`norm_stats.json`, so the component cannot import itself or find its own
assets. Its README documents the clean names throughout; the suffixes are
packaging damage, not the author's layout.

The unified backend works around this at runtime and does not need the rename.
This script exists so Component 02 also runs *standalone* again -- its own
`backend/server.py`, its audit suite, and its bundled test-set browsing.

SAFETY
------
- Dry run by default. Nothing moves without --apply.
- Refuses to start if any rename would overwrite an existing path.
- Writes a JSON manifest of every rename, so --undo restores the previous
  state exactly.
- `__pycache__` directories are deleted rather than renamed: they are
  regenerated on demand and their stale contents would shadow the renamed
  modules.

USAGE
-----
    python scripts/normalize_component02_paths.py             # preview
    python scripts/normalize_component02_paths.py --apply
    python scripts/normalize_component02_paths.py --undo .cache/rename_manifest.json
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import time
from pathlib import Path
from typing import List, Optional, Tuple

BACKEND_DIR = Path(__file__).resolve().parent.parent
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

SUFFIX = " (1)"


def cleaned(name: str) -> Optional[str]:
    """`models (1).py` -> `models.py`; `src (1)` -> `src`; else None."""
    if name.endswith(SUFFIX):
        return name[: -len(SUFFIX)]
    marker = SUFFIX + "."
    if marker in name:
        index = name.rindex(marker)
        return name[:index] + name[index + len(SUFFIX):]
    return None


def collect(root: Path) -> Tuple[List[Path], List[Path], List[Path]]:
    """Return (pycache_dirs, files, dirs). Dirs are deepest-first."""
    pycache, files, dirs = [], [], []
    for path in root.rglob("*"):
        # Skip installed npm packages. They carry the same suffix, but they are
        # regenerated by `npm install` and renaming thousands of vendored files
        # risks breaking package resolution for no benefit.
        if any(part in ("node_modules", "node_modules" + SUFFIX) for part in path.parts):
            continue
        if path.name == "__pycache__" or path.name == "__pycache__" + SUFFIX:
            if path.is_dir():
                pycache.append(path)
            continue
        if any(part in ("__pycache__", "__pycache__" + SUFFIX) for part in path.parts):
            continue
        if cleaned(path.name) is None:
            continue
        (dirs if path.is_dir() else files).append(path)
    # Rename files before their parents, and deepest directories first, so a
    # path recorded now is still valid when its turn comes.
    files.sort(key=lambda p: len(p.parts), reverse=True)
    dirs.sort(key=lambda p: len(p.parts), reverse=True)
    return pycache, files, dirs


def check_collisions(paths: List[Path]) -> List[Tuple[Path, Path]]:
    clashes = []
    for path in paths:
        target = path.parent / cleaned(path.name)
        if target.exists():
            clashes.append((path, target))
    return clashes


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=None,
                        help="Component 02 directory (default: discovered from settings)")
    parser.add_argument("--apply", action="store_true", help="perform the renames")
    parser.add_argument("--undo", metavar="MANIFEST",
                        help="restore the suffixes recorded in a manifest")
    parser.add_argument("--manifest", default=None,
                        help="where to write the rename manifest")
    args = parser.parse_args()

    if args.undo:
        return undo(Path(args.undo))

    from cvxai.settings import get_settings

    settings = get_settings()
    root = Path(args.root) if args.root else settings.ecg_root
    if root is None or not root.is_dir():
        print("Component 02 root not found. Pass --root explicitly.", file=sys.stderr)
        return 2

    print("root: %s" % root)
    pycache, files, dirs = collect(root)
    print("  __pycache__ dirs to delete : %d" % len(pycache))
    print("  files to rename            : %d" % len(files))
    print("  directories to rename      : %d" % len(dirs))

    clashes = check_collisions(files + dirs)
    if clashes:
        print("\nREFUSING: %d rename(s) would overwrite an existing path:" % len(clashes),
              file=sys.stderr)
        for source, target in clashes[:10]:
            print("  %s\n    -> %s (exists)" % (source, target), file=sys.stderr)
        return 1

    if not args.apply:
        print("\nDry run. Sample of what would change:")
        for path in (files[:3] + dirs[:3]):
            print("  %s\n    -> %s" % (path.name, cleaned(path.name)))
        print("\nRe-run with --apply to perform %d renames." % (len(files) + len(dirs)))
        return 0

    for path in pycache:
        shutil.rmtree(path, ignore_errors=True)

    started = time.perf_counter()
    records = []
    for path in files + dirs:
        target = path.parent / cleaned(path.name)
        path.rename(target)
        records.append({"from": str(path), "to": str(target)})

    # The component root itself, last. Its own audit scripts resolve the
    # package as `<grandparent>/Component_02`, so they only import when the
    # directory carries exactly that name. Renaming it last keeps the manifest
    # replayable: undo restores the root first, which makes every child path
    # recorded above valid again.
    root_target = root.parent / cleaned(root.name) if cleaned(root.name) else None
    if root_target and not root_target.exists():
        root.rename(root_target)
        records.append({"from": str(root), "to": str(root_target)})
        print("  component root: %s -> %s" % (root.name, root_target.name))

    # Timestamped, never overwritten: a second run must not clobber the record
    # of the first, or the earlier renames become unreversible.
    manifest_path = Path(args.manifest) if args.manifest else (
        settings.cache_dir / ("component02_rename_%s.json"
                              % time.strftime("%Y%m%d_%H%M%S")))
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    if manifest_path.exists() and not args.manifest:
        manifest_path = manifest_path.with_name(
            manifest_path.stem + "_%d.json" % int(time.time() % 1000))
    manifest_path.write_text(json.dumps(
        {"root": str(root), "created": time.strftime("%Y-%m-%dT%H:%M:%S"),
         "renames": records}, indent=1), encoding="utf-8")

    print("\nrenamed %d paths in %.1fs" % (len(records), time.perf_counter() - started))
    print("manifest: %s" % manifest_path)
    print("undo:     python scripts/normalize_component02_paths.py --undo \"%s\""
          % manifest_path)
    return 0


def undo(manifest_path: Path) -> int:
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    records = payload["renames"]
    # Reverse order: parents were renamed last, so they are restored first.
    restored = 0
    for record in reversed(records):
        target, source = Path(record["to"]), Path(record["from"])
        if target.exists() and not source.exists():
            target.rename(source)
            restored += 1
    print("restored %d of %d paths" % (restored, len(records)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
