import { useState } from 'react'
import Header from './components/Header'
import UploadZone from './components/UploadZone'
import ResultsPanel from './components/ResultsPanel'

function App() {
  const [isLoading, setIsLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [originalImgUrl, setOriginalImgUrl] = useState(null)
  // Projection drives the operating point. Left blank the backend uses the
  // global threshold rather than guessing -- guessing PA on a bedside film
  // would under-call cardiomegaly on the patients least able to tolerate it.
  const [view, setView] = useState('')

  const handleUpload = async (file) => {
    setIsLoading(true)
    setResult(null)
    
    // Set local preview
    const reader = new FileReader()
    reader.onload = (e) => setOriginalImgUrl(e.target.result)
    reader.readAsDataURL(file)

    const formData = new FormData()
    formData.append('file', file)
    if (view) formData.append('view', view)

    try {
      // Proxy in vite.config.js forwards /predict to localhost:8000
      const response = await fetch('/predict', {
        method: 'POST',
        body: formData,
      })
      
      if (!response.ok) {
        throw new Error(`Server responded with ${response.status}`)
      }
      
      const data = await response.json()
      setResult(data)
    } catch (error) {
      console.error('Error during prediction:', error)
      alert('Error analyzing image. Please ensure the backend is running on port 8000.')
    } finally {
      setIsLoading(false)
    }
  }

  const handleReset = () => {
    setResult(null)
    setOriginalImgUrl(null)
  }

  return (
    <div className="app-shell">
      <Header />
      <main className="page">
        {!result ? (
          <>
            <section className="hero rise-in">
              <div>
                <p className="eyebrow">Clinical imaging assistant</p>
                <h2 className="hero-title">Cardiomegaly analysis with clarity and context.</h2>
                <p className="hero-subtitle">
                  Upload a frontal chest X ray to receive classification, GradCAM visual focus, and a structured
                  report summary generated by the model stack.
                </p>
              </div>
              <div className="hero-meta">
                <span className="pill">ConvNeXt image model</span>
                <span className="pill">GradCAM explanations</span>
                <span className="pill">BioBART report text</span>
                <span className="pill">Cardiomegaly AUROC 0.9189</span>
              </div>
            </section>
            <section className="content-grid rise-in-1">
              <div>
                <UploadZone onUpload={handleUpload} isLoading={isLoading} />

                {/* Projection selector - applies the per-projection operating point */}
                <div className="card" style={{ marginTop: '16px', padding: '18px 20px' }}>
                  <p className="eyebrow" style={{ marginBottom: '12px' }}>Projection</p>
                  <div className="segmented">
                    {[
                      { v: '', label: 'Not specified' },
                      { v: 'PA', label: 'PA - standing' },
                      { v: 'AP', label: 'AP - bedside' },
                    ].map((o) => (
                      <button
                        key={o.v}
                        onClick={() => setView(o.v)}
                        disabled={isLoading}
                        className={`segmented-btn ${view === o.v ? 'active' : ''}`}
                      >
                        {o.label}
                      </button>
                    ))}
                  </div>
                  <p className="panel-note" style={{ marginTop: '10px', marginBottom: 0 }}>
                    AP films magnify the cardiac silhouette, so a different decision
                    threshold applies - as in clinical practice, where cardiomegaly is
                    CTR &gt; 0.50 on PA and &gt; 0.55 on AP.
                  </p>
                </div>
              </div>
              <div className="card">
                <h3 className="card-title">What you receive</h3>
                <p className="card-subtitle">
                  A focused, minimal workflow designed for rapid review and clear decision support.
                </p>
                <ul className="info-list">
                  <li>Cardiomegaly classification with co-pathology findings.</li>
                  <li>GradCAM overlay to highlight regions that influenced the decision.</li>
                  <li>Generated report summary with impression and findings.</li>
                  <li>PNG or JPG input, optimized for frontal chest X rays.</li>
                </ul>
              </div>
            </section>
          </>
        ) : (
          <section className="rise-in">
            <div className="results-toolbar">
              <button onClick={handleReset} className="ghost-button">Analyze another image</button>
              <span className="eyebrow">Session output ready</span>
            </div>
            <ResultsPanel result={result} originalImg={originalImgUrl} />
          </section>
        )}
      </main>
    </div>
  )
}

export default App
