import { useState } from 'react'
import Header from './components/Header'
import UploadZone from './components/UploadZone'
import ResultsPanel from './components/ResultsPanel'

function App() {
  const [isLoading, setIsLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [originalImgUrl, setOriginalImgUrl] = useState(null)

  const handleUpload = async (file) => {
    setIsLoading(true)
    setResult(null)
    
    // Set local preview
    const reader = new FileReader()
    reader.onload = (e) => setOriginalImgUrl(e.target.result)
    reader.readAsDataURL(file)

    const formData = new FormData()
    formData.append('file', file)

    try {
      // Proxy in vite.config.js forwards /predict to localhost:8000
      const response = await fetch('/predict', {
        method: 'POST',
        body: formData,
      })
      
      if (!response.ok) {
        throw new Error(`Server responded with ${response.status}`)
      }
      
      const data = await response.json()
      setResult(data)
    } catch (error) {
      console.error('Error during prediction:', error)
      alert('Error analyzing image. Please ensure the backend is running on port 8000.')
    } finally {
      setIsLoading(false)
    }
  }

  const handleReset = () => {
    setResult(null)
    setOriginalImgUrl(null)
  }

  return (
    <div className="app-shell">
      <Header />
      <main className="page">
        {!result ? (
          <>
            <section className="hero rise-in">
              <div>
                <p className="eyebrow">Clinical imaging assistant</p>
                <h2 className="hero-title">Cardiomegaly analysis with clarity and context.</h2>
                <p className="hero-subtitle">
                  Upload a frontal chest X ray to receive classification, GradCAM visual focus, and a structured
                  report summary generated by the model stack.
                </p>
              </div>
              <div className="hero-meta">
                <span className="pill">ConvNeXt image model</span>
                <span className="pill">GradCAM explanations</span>
                <span className="pill">BART - base report text</span>
              </div>
            </section>
            <section className="content-grid rise-in-1">
              <UploadZone onUpload={handleUpload} isLoading={isLoading} />
              <div className="card">
                <h3 className="card-title">What you receive</h3>
                <p className="card-subtitle">
                  A focused, minimal workflow designed for rapid review and clear decision support.
                </p>
                <ul className="info-list">
                  <li>Cardiomegaly classification with co-pathology findings.</li>
                  <li>GradCAM overlay to highlight regions that influenced the decision.</li>
                  <li>Generated report summary with impression and findings.</li>
                  <li>PNG or JPG input, optimized for frontal chest X rays.</li>
                </ul>
              </div>
            </section>
          </>
        ) : (
          <section className="rise-in">
            <div className="results-toolbar">
              <button onClick={handleReset} className="ghost-button">Analyze another image</button>
              <span className="eyebrow">Session output ready</span>
            </div>
            <ResultsPanel result={result} originalImg={originalImgUrl} />
          </section>
        )}
      </main>
    </div>
  )
}

export default App
