"""
All the paths and settings for the backend live here.

This is a separate deployment from the older ../../backend folder. It doesn't
read or write anything in there. It serves the retrained models:

    classifier        Stage 5    mean AUROC 0.8554  (old one was 0.8251)
    report generator  Stage 11   CheXbert F1 0.5939 (old one scored ROUGE-L
                                 0.2740, which was actually below the 0.2769
                                 you get from a fixed paragraph)

It also adds per-projection thresholds, which the old backend didn't have.
"""
from pathlib import Path

# Component_01/Component_01/
PROJECT_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = PROJECT_ROOT.parent                       # Component_01/

# ---------------------------------------------------------------------------
# Model weights. Stage 11 is what we want; Stage 4 is only a fallback for when
# Stage 11 hasn't been downloaded from Drive yet. The service prints which one
# it loaded, because quietly serving the old model would make every reported
# number wrong.
# ---------------------------------------------------------------------------
CLASSIFIER_WEIGHTS = PROJECT_ROOT / "checkpoints" / "stage5" / "best.pt"
REPORTGEN_STAGE11 = PROJECT_ROOT / "checkpoints" / "stage11" / "best.pt"
REPORTGEN_STAGE4 = PROJECT_ROOT / "checkpoints" / "stage4" / "best.pt"

THRESHOLDS_JSON = Path(__file__).resolve().parent / "thresholds.json"

# The deferral policy is optional. If it isn't there the service still runs,
# just without the "refer to radiologist" feature. Generated by
# stage13_deferral.py.
DEFERRAL_POLICY_JSON = PROJECT_ROOT / "reports" / "stage13" / "deferral_policy.json"
TEST_MANIFEST = PROJECT_ROOT / "training_manifest" / "manifest_test.csv"
TEST_IMAGE_DIR = REPO_ROOT / "data" / "output" / "cardio_image_384"

# Ground truth = the radiologist's original text, exactly as dictated, prior
# study references and all. Deliberately NOT manifest_test.csv, whose report
# column holds our Stage 1 cleaned version. Showing the cleaned text as "ground
# truth" would compare the model against our own preprocessing instead of
# against the radiologist. Opened read-only; we never write to it.
#
# There is a local copy inside review_cases/ so the folder can be handed to
# someone without the parent directory. Falls back to the original location if
# that copy isn't there.
ORIGINAL_TEST_CSV = PROJECT_ROOT / "review_cases" / "cardio_test.csv"
if not ORIGINAL_TEST_CSV.exists():
    ORIGINAL_TEST_CSV = REPO_ROOT / "data" / "output" / "cardiomegaly_dataset" / "cardio_test.csv"

# ---------------------------------------------------------------------------
# Model settings
# ---------------------------------------------------------------------------
IMG_SIZE = 384
DECODER_NAME = "GanjinZero/biobart-v2-base"
NUM_VISUAL_TOKENS = 144                                # 12x12 grid

LABEL_COLS = ["Cardiomegaly", "Edema", "Pleural_Effusion", "Atelectasis",
              "Consolidation", "Lung_Opacity", "Pneumonia", "Pneumothorax"]
NUM_LABELS = len(LABEL_COLS)

# These three get top billing in the dashboard. The rest are still computed and
# returned in the response.
PRIMARY_PATHOLOGIES = ["Cardiomegaly", "Edema", "Pleural_Effusion"]
PRIMARY_INDICES = [LABEL_COLS.index(p) for p in PRIMARY_PATHOLOGIES]

# A NOTE ON PREPROCESSING
# The old backend normalised with ImageNet mean/std. That's wrong for grayscale
# X-rays -- we measured it as 4.4x worse variance across images than using raw
# pixels. This deployment imports cxr_transforms and uses per-image z-score,
# the same transform the models were trained with. Any mismatch here would
# degrade every prediction with no error message, so we never redefine the
# transform locally.

# ---------------------------------------------------------------------------
# Text generation (Stage 4B ablation: greedy beat beam-4 on 5 of 7 metrics)
# ---------------------------------------------------------------------------
GEN_NUM_BEAMS = 1
GEN_MAX_TOKENS = 192
GEN_MIN_TOKENS = 24
GEN_NO_REPEAT_NGRAM = 3

# ---------------------------------------------------------------------------
# Measured performance, shown in /api/health and the UI footer
# ---------------------------------------------------------------------------
MODEL_STATS = {
    "classifier": {
        "mean_auroc": 0.8554,
        "cardiomegaly_auroc": 0.9189,
        "cardiomegaly_sensitivity": 0.923,
        "cardiomegaly_ci": [0.9112, 0.9265],
    },
    "report_generator": {
        "chexbert_micro_f1_14": 0.5939,
        "cardiomegaly_report_f1": 0.8287,
        "rouge_l": 0.2896,
        "constant_string_baseline": 0.2641,
        "prior_hallucination_rate": 0.0,
    },
    "test_set_n": 4722,
}

# The measured AP/PA gap. Drives the reliability flag in the UI.
PROJECTION_AUROC = {"AP": 0.8224, "PA": 0.8864}
PROJECTION_GAP = 0.0639

CORS_ORIGINS = ["http://localhost:5173", "http://127.0.0.1:5173",
                "http://localhost:5174", "http://127.0.0.1:5174"]
